theme: jekyll-theme-slate

title: Platinum Sheets
description: Sharing thoughts and music via blog posts and transcriptions

baseurl: /platinum-sheets

permalink: pretty

plugins:
  - jemoji

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/images/sheets"
    values:
      sheet: true
  - scope:
      path: "assets/images/sheets/C"
    values:
      sheet_part: C
  - scope:
      path: "assets/images/sheets/Vocals"
    values:
      sheet_part: Vocals
  - scope:
      type: "posts"
    values:
      parts:
        - C
